import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import { TooltipProvider } from '@/components/ui/tooltip';
import './globals.css';

const figTree = Figtree({
  variable: '--font-figtree',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${figTree.className} min-h-dvh h-full antialiased`}
    >
      <body className="min-h-dvh h-full bg-background-normal">
        <TooltipProvider>
          <ToastContainer position="top-right" autoClose={3000} />
          {children}
        </TooltipProvider>
      </body>
    </html>
  );
}
